### ISSUE TITLE
/home in rpool/ROOT/debian not empty after install

### ISSUE THREAD

**Issue by gitbisector** [zfsonlinux/debian-installers#4]
Ran the install again today in a fresh VM with latest mini.iso

Found that rpool/home got created but not mounted before the first user was created by the installer. That put the first user under rpool/ROOT/debian/home/ which made that directory non-empty preventing subsequent mounting when booting into the installed OS.

**Comment by FransUrbo** [comment]
Thanx, I'll have a look. It is most likely a problem somewhere in the <code>partman-zfs</code> code… Finding it shouldn't be to difficult (I hope).

**Comment by beren12** [comment]
Debian by default puts a reminder that /home isn't mounted in the rootfs/home/user if you tell the install to use a separate /home. Most people never notice until they freak out when $home is empty because /home wasn't mounted.

**Comment by FransUrbo** [comment]
> Debian by default puts a reminder that /home isn't mounted in the rootfs/home/user if you tell the install to use a separate /home.
> 
> Unfortunately, I don't think that's the case here.

The problem seems to be the way the Debian Installer (D-I) is constructed. Once 'partman' (the part of D-I that deals with partition disks and setup raids/lvms/zfs etc) is done, it unmounts EVERYTHING partman just created (it's not really supposed to create anything, only record what needs to be done for the next stage).

But I can't do that, because D-I and partman only understands block devices. Which a zfs pool and filesystem ISN'T. The kFreeBSD folks (which partman-zfs I slightly (!) modified for Linux) solved this by enforcing to install on a ZVOL. But I neither wanted or thought that was a good/clean way. So part of the modification was just to make it understand ZFS filesystems.

After that, when you continue the installation and leave the partitioner (partman), it (D-I) then puts a filesystem (where such is needed - which it of course isn't in the ZoL case, but is for kFreeBSD ZFS) on the devices and THEN mounts everything again.

This works because we/I use 'legacy' for the root filesystem etc. That was the only way that worked (although I had to 'fake' it a little to get that to work - perfectly fine for root/OS fs etc). I could then create the filesystem and 'figure out' 'fstab' entries for each of those filesystems. BUT, because the home fs is a 'native' fs, this can't be done, it needs to be mounted differently (simply, it needs the "-o zfsutil" option to 'mount' OR use "zfs mount" instead - something I can't do without some rewrites outside partman-zfs which is the only part I wanted to modify).

Therefor, when partman is mounting everything again, it 'forgets' the home fs (because it is unknown to the rest of D-I - it can't be 'recorded' as such, because it's not a block device).

I've actually known about this issue for some time, but I have … 'ignored' and (half deliberately) 'forgot' about this (pushed it out of my mind as it where). Because there is not much I can do about this, other than rewrite large parts of partman-base (I think it was). I neither wanted or could do that (at this moment - someone probably have to once ZoL is in the official Debian GNU/Linux archive - which shouldn't "be long now"). It would also be quite an undertaking (in man-hours).

So for now, this is unfortunately something I think we'll have to live with. It shouldn't be to big a deal, the user home directory one creates during install is quite small so it should be easy to move out of the way, mount the ZFS home filesystem and then move the homedir back.

OR, I make sure we don't create a user (and therefor no homdir) at all - let the admin do that once the machine is up and running. Because once the installer is finished, and we boot into the new install/OS, the homedir is mounted automatically (if there's nothing in the mount point - which there wouldn't be if we don't create a user).
