### ISSUE TITLE
Boot from snapshot mounts both snapshot and real fs

### ISSUE THREAD

**Issue by gitbisector** [zfsonlinux/debian-installers#5]
The mount-points for the (boot,usr,var)-snapshots are 'none' but the original ones are set for 'legacy' which seems to cause this trouble:

```
root@debian:~# zfs list
NAME                              USED  AVAIL  REFER  MOUNTPOINT
rpool                             798M  14.8G    19K  none
rpool/ROOT                        797M  14.8G    19K  none
rpool/ROOT/debian                 797M  14.8G   155M  /
rpool/ROOT/debian/boot           32.2M  14.8G  32.2M  legacy
rpool/ROOT/debian/boot_prestine     1K  14.8G  32.2M  none
rpool/ROOT/debian/usr             490M  14.8G   490M  legacy
rpool/ROOT/debian/usr_prestine     70K  14.8G   490M  none
rpool/ROOT/debian/var             119M  14.8G   119M  legacy
rpool/ROOT/debian/var_prestine     42K  14.8G   118M  none
rpool/ROOT/debian_prestine        414K  14.8G   155M  none
rpool/home                         25K  14.8G    25K  /home
```

```
root@debian:~# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=126627,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=102696k,mode=755)
rpool/ROOT/debian_prestine on / type zfs (rw,relatime,xattr,noacl)
rpool/ROOT/debian/boot_prestine on /boot type zfs (rw,relatime,xattr,noacl)
rpool/ROOT/debian/usr_prestine on /usr type zfs (rw,relatime,xattr,noacl)
rpool/ROOT/debian/var_prestine on /var type zfs (rw,relatime,xattr,noacl)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /run/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=205380k)
rpool/ROOT/debian/boot on /boot type zfs (rw,relatime,xattr,noacl)
rpool/ROOT/debian/usr on /usr type zfs (rw,relatime,xattr,noacl)
rpool/ROOT/debian/var on /var type zfs (rw,relatime,xattr,noacl)
rpc_pipefs on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
rpool/home on /home type zfs (rw,relatime,xattr,noacl)
```

**Comment by FransUrbo** [comment]
I'm fairly certain I should call this 'feature' :). One, because if you're booting from a snapshot, you're _most likely_ intending to fix 'something' (which you COULD technically do in the 'real fs' by using chroot). And two, I don't see any way to avoid this.

If it's 'path' (as in 'native'), it will be automatically mounted by <code>zfs-mount</code>. If it's <code>legacy</code> it should either be mounted from <code>/etc/fstab</code> or from the initrd. I guess, in the latter case I _could_ write logic to try to avoid this, but since point one, I'm not sure I should...

**Comment by gitbisector** [comment]
Trouble is GLIBC got upgraded between 'live' and 'snapshot' and the legacy mounts seem to be 'on top off' the snapshot ones so the system is not stable with / from the snapshot and others parts from 'live'

**Comment by FransUrbo** [comment]
Oh, ouch! That's no good. Do you mount your filesystems from <code>/etc/fstab</code> or in the initrd (via the <code>ZFS_INITRD_ADDITIONAL_DATASETS</code> or possibly even automatic)?

**Comment by FransUrbo** [comment]
I've been able to reproduce this. UNFORTUNATELY, I have no idea how to fix this1

There is no problem with the initrd. It does the job correctly - only mounting the new cloned filesystem. The initscript ALSO does the correct job (as far as I can tell). The problem is the legacy mount point entries in <code>/etc/fstab</code>. They are mounted outside of the ZoL code…

_Most probably_ they are mounted in the <code>/etc/init.d/mountall.sh</code> script (which mounts all local filesystems and is run long before <code>zfs-mount</code> is run). I can not (and is not allowed to) change this - I don't "own" it!.

**Comment by FransUrbo** [comment]
I'm going to close this (for now). If someone have a good, working solution or idea about this, I'd love to hear it. But for now, it's not much I can do about this.

**Comment by gitbisector** [comment]
Been thinking about this some more (in combination with #7)

If the naming of the cloned FSs were like this instead:

```
rpool/ROOT/debian_prestine
rpool/ROOT/debian_prestine/boot
rpool/ROOT/debian_prestine/usr
rpool/ROOT/debian_prestine/var
```

Then maybe renaming the 'live' zfs to put it out of harm's way is ok for repairs? 
Something like: `zfs rename rpool/ROOT/debian rpool/ROOT/debian_recover0`

Once the live fs is out of the way renaming the cloned fs to the
original: `zfs rename rpool/ROOT/debian_somesnapshot rpool/ROOT/debian`
makes sure any references like those in /etc/fstab are all consistent

The logic in grub would go like this:

```
    if @somesnapshot requested then 
        if(there is no existing debian_somesnapshot clone)
            clone debian@somesnapshot into rpool/ROOT/debian_somesnapshot
        zfs rename rpool/ROOT/debian rpool/ROOT/debian_recover(N++)
        zfs rename rpool/ROOT/debian_somesnapshot rpool/ROOT/debian
    fi
    boot as usual
```

Then getting the live fs back (after repairs) would be a matter of booting debian@recover0

**Comment by FransUrbo** [comment]
I'm not touching the real/live filesystems! It's just to dangerous to do in an automated fashion. Sooner or later, someone, somewhere is going to do something I didn't anticipate (like … "just booting a snapshot to test/look/compare something and then hard reset without cleaning up"), and the filesystems are 'gone' (as in, not where the user expected them :).

Technically, it's a better idea to NOT have the fstab entries there in the first place. Unfortunately, the way D-I is designed/built, I can't do much about that (at the moment).

As I've described elsewhere, the fstab entries are there because D-I/partman doesn't understand non-block devices and to be able to mount them after partman is finished and the 'real' installation can begin, it needs the fstab entries. But because all that is taken care of in the initrd, it's superfluous information for ZFS/ZoL….

**Comment by gitbisector** [comment]
Point taken. Instead I now remove those entries from /etc/fstab after the 1st boot of the installed system. That makes sure subsequent snapshots can boot clean without extraneous mounts of the live ones.

**Comment by FransUrbo** [comment]
> Point taken. Instead I now remove those entries from /etc/fstab after the 1st boot of the installed system.
> 
> It's annoying, I know. But this installer was never meant to be 'perfect'. It was more of a "proof of concept". AND somewhat better than the manual approach described in the HOWTOs in pkg-zfs :D

But please keep the issues/bug reports coming… I appreciate it!

And those I've closed isn't wasted. I'll keep them in mind when I do it "for real" (eventually :) in the official Debian GNU/Linux one, as soon as they/we have accepted them into the archives..
