### ISSUE TITLE
booting from a 2nd snapshot clones stale snapshots again

### ISSUE THREAD

**Issue by gitbisector** [zfsonlinux/debian-installers#7]
After booting from @prestine earlier just now I booted from @06411 snapshot:

```
root@debian:~# zfs list
NAME                                    USED  AVAIL  REFER  MOUNTPOINT
rpool                                  2.20G  13.4G    19K  none
rpool/ROOT                             2.20G  13.4G    19K  none
rpool/ROOT/debian                      2.20G  13.4G   191M  /
rpool/ROOT/debian/boot                 62.0M  13.4G  33.3M  legacy
rpool/ROOT/debian/boot_06411              1K  13.4G  32.3M  none
rpool/ROOT/debian/boot_prestine           1K  13.4G  32.2M  none
rpool/ROOT/debian/boot_prestine_06411     1K  13.4G  32.2M  none
rpool/ROOT/debian/usr                  1.19G  13.4G   772M  legacy
rpool/ROOT/debian/usr_06411              66K  13.4G   491M  none
rpool/ROOT/debian/usr_prestine           70K  13.4G   490M  none
rpool/ROOT/debian/usr_prestine_06411      1K  13.4G   490M  none
rpool/ROOT/debian/var                   633M  13.4G   434M  legacy
rpool/ROOT/debian/var_06411              83K  13.4G   209M  none
rpool/ROOT/debian/var_prestine           42K  13.4G   118M  none
rpool/ROOT/debian/var_prestine_06411      1K  13.4G   118M  none
rpool/ROOT/debian_06411                 408K  13.4G   155M  none
rpool/ROOT/debian_prestine              416K  13.4G   155M  none
rpool/home                               25K  13.4G    25K  /home
```

I certainly understand why we get this side effect. There's currently no way for the loader to know the minimum set that needs cloning. Any chance that can be stored and read from some zfs pool properties?

**Comment by FransUrbo** [comment]
> I certainly understand why we get this side effect. There's currently no way for the loader to know the minimum set that needs cloning. Any chance that can be stored and read from some zfs pool properties?

Technically I guess it should be possible. But I'm not going to. It is VERY (!!) dangerous to start to delete filesystems etc 'automatically'. I really, REALLY think that this is and should be an administrator cleanup procedure… 

But let me think about that a little.

Registering the filesystems we 'just' created (when doing the clone) 'somewhere' and then on the subsequent boot destroy them wether we're booting from a snapshot then or not… Should be 'safe'.

The next question is then WHERE to save this. Can't do it in the initrd, because that's a ram fs and is temporary. Can't do it in the cloned fs (?) because we can't start traversing filesystems 'wildly' when we're booting (I have 750+ filesystems and it 'takes a while' to list :).

Doing a 'match and check' isn't a good idea either, because even if we know the filesystem we're just about to mount, we'd need a list of all it's snapshots (which can be _a lot_). Comparing the current fs and it's snapshot with <code>current fs</code>_<code>snapshotX</code> is just going to take to long.

Can't do it in the 'real' fs, because that might be rollbacked (either by the admin or the initrd - if you're using the dailies now, you should have the <code>rollback=yes</code> option now to do this automatically) 'at any time'.

If/when using the <code>rollback</code> option will in some way avoid this and make the 'restore' procedure easier and faster.

**Comment by FransUrbo** [comment]
I'm going to close this (for now). If someone have a good, working solution or idea about this, I'd love to hear it. But for now, it's not much I can (or want to) do about this.

**Comment by gitbisector** [comment]
Turbo, I know you closed this but I think there is a simple elegant fix. Building on your work I put the snapshot label at what seems a more natural spot than simply tacking it on at the end. 

I wrote the code for it today tested, locally and published it here: https://github.com/gitbisector/pkg-zfs/commit/ddcea68ca342b71d9c8cf055ec0ca48ae79a94b5

(update: made one more cleanup commit https://github.com/gitbisector/pkg-zfs/commits/alternate_snap_hier/scripts/zfs-initramfs/scripts/zfs)

Not sure how to put in a pull request without a recent branch point in your repo. Can you help there?

The idea is to keep the cloned FSs out of the base namespace. It has the nice side effect that cleanup is also a single command: `zfs destroy -r rpool/ROOT/debian_prestine`

The result is like this after booting from 'prestine' snapshot:

```
root@debian:~# zfs list
NAME                              USED  AVAIL  REFER  MOUNTPOINT
rpool                             890M  14.8G    19K  none
rpool/ROOT                        889M  14.8G    19K  none
rpool/ROOT/debian                 889M  14.8G   155M  /
rpool/ROOT/debian/boot           32.3M  14.8G  32.3M  legacy
rpool/ROOT/debian/usr             491M  14.8G   491M  legacy
rpool/ROOT/debian/var             210M  14.8G   209M  legacy
rpool/ROOT/debian_prestine        653K  14.8G   155M  none
rpool/ROOT/debian_prestine/boot     1K  14.8G  32.3M  none
rpool/ROOT/debian_prestine/usr     67K  14.8G   491M  none
rpool/ROOT/debian_prestine/var    120K  14.8G   209M  none
rpool/home                         19K  14.8G    19K  /home
root@debian:~# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=126624,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=102696k,mode=755)
rpool/ROOT/debian_prestine on / type zfs (rw,relatime,xattr,noacl)
rpool/ROOT/debian_prestine/boot on /boot type zfs (rw,relatime,xattr,noacl)
rpool/ROOT/debian_prestine/usr on /usr type zfs (rw,relatime,xattr,noacl)
rpool/ROOT/debian_prestine/var on /var type zfs (rw,relatime,xattr,noacl)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /run/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=205380k)
rpool/ROOT/debian/boot on /boot type zfs (rw,relatime,xattr,noacl)
rpool/ROOT/debian/usr on /usr type zfs (rw,relatime,xattr,noacl)
rpool/ROOT/debian/var on /var type zfs (rw,relatime,xattr,noacl)
rpc_pipefs on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
```

**Comment by FransUrbo** [comment]
> Not sure how to put in a pull request without a recent branch point in your repo. Can you help there?
> 
> Don't think that can be done :(
> The idea is to keep the cloned FSs out of the base namespace. It has the nice side effect that cleanup is also a single command: zfs destroy -r rpool/ROOT/debian_prestine
> 
> It is indeed prettier, but I really doesn't solve anything/much…
> rpool/ROOT/debian                 889M  14.8G   155M  /
> rpool/ROOT/debian/boot           32.3M  14.8G  32.3M  legacy
> rpool/ROOT/debian/usr             491M  14.8G   491M  legacy
> rpool/ROOT/debian/var             210M  14.8G   209M  legacy
> rpool/ROOT/debian_prestine        653K  14.8G   155M  none
> rpool/ROOT/debian_prestine/boot     1K  14.8G  32.3M  none
> rpool/ROOT/debian_prestine/usr     67K  14.8G   491M  none
> rpool/ROOT/debian_prestine/var    120K  14.8G   209M  none
> Let's for arguments sake that we have … fifty snapshots saved for "rpool/ROOT/debian" (recursively).

We need to get that list (we only need to get that list for the root FS, we're already assuming that all those snapshots MUST exist for any sub-filesystem for this to work) and then try them one by one, replacing the "@" for "_" and compare if that matches "rpool/ROOT/debian_prestine".

And can we absolutely and everywhere guarantee that that WILL be the clone we've created earlier? Probably, but I'm not so sure I want to bet on that… We can limit the danger with this to make sure that the "origin" property matches "rpool/ROOT/debian@prestine". But that means even more work (and more time). _I think_ that that is to much work, with not that much gain. Especially doing it _every time_ we boot (because we don't know if "last time" was a "snapshot boot")...

But I'm going to look at your commit and most likely apply that anyway, because it's "prettier", and it makes it easier for the administrator to clean up afterwards.

**Comment by FransUrbo** [comment]
Applied to <code>snapshot/debian/wheezy/0.6.4-1-10-wheezy</code> and <code>snapshot/debian/jessie/0.6.4-1-10</code> as:

```
zfs-linux (0.6.4-1-10-wheezy) wheezy; urgency=low

  * Change hierarchical naming of clones for boot-from-snapshot.
    Thanx to 'bisector' for patch.

 -- Turbo Fredriksson <turbo@debian.org>  Thu, 30 Apr 2015 13:27:26 +0200
```

**Comment by gitbisector** [comment]
Thanks for taking my patch.  Even without the extra work you suggest, booting from different snapshots now no longer causes recursive cloning of every snapshot ever booted from(and not yet cleaned up).
